# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Avocat', '0001_initial'),
        ('Dossier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAvocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rôle_avocat', models.CharField(choices=[('principal', 'Principal'), ('assistant', 'Assistant')], max_length=20)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avocat.avocat')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier')),
            ],
        ),
    ]
