# Generated by Django 5.2.4 on 2025-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierAvocat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieravocat',
            name='rôle_avocat',
            field=models.CharField(choices=[('expert_metier', 'Expert métier'), ('personnel_administratif', 'Personnel administratif')], max_length=30),
        ),
    ]
