# Generated by Django 5.2.4 on 2025-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('datenaissance', models.DateField(blank=True, null=True)),
                ('type_client', models.CharField(blank=True, choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=25, null=True)),
            ],
        ),
    ]
