# Generated by Django 5.2.4 on 2025-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type_document', models.CharField(choices=[('plainte', 'Plainte'), ('preuve', 'Preuve'), ('contrat', 'Contrat'), ('autre', 'Autre')], default='plainte', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
