# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Document', '0001_initial'),
        ('Dossier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier'),
        ),
    ]
