# Generated by Django 5.2.4 on 2025-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('preuve', 'Preuve'), ('contrat', 'Contrat'), ('autre', 'Autre'), ('piece_du_client', 'Pièce du client'), ('offre_technique', 'Offre technique'), ('offre_financiere', 'Offre financière'), ('cv_expert', 'CV Expert'), ('profil_cabinet', 'Profil Cabinet'), ('fiche_de_paiement', 'Fiche de paiement'), ('facture', 'Facture'), ('fiche_de_travail', 'Fiche de travail'), ('diplome_expert', 'Diplôme Expert'), ('attestation_de_bon_fin', 'Attestation de bon fin'), ('tdr', 'TDR')], default='plainte', max_length=50),
        ),
    ]
