# Generated by Django 5.2.4 on 2025-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
