# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Avocat', '0001_initial'),
        ('Client', '0001_initial'),
        ('Dossier', '0001_initial'),
        ('DossierAvocat', '0001_initial'),
        ('DossierClient', '0001_initial'),
        ('StatutDossier', '0001_initial'),
        ('TypeAffaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='avocats',
            field=models.ManyToManyField(related_name='dossiers', through='DossierAvocat.DossierAvocat', to='Avocat.avocat'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='clients',
            field=models.ManyToManyField(related_name='dossiers', through='DossierClient.DossierClient', to='Client.client'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='statut_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StatutDossier.statutdossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_affaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TypeAffaire.typeaffaire'),
        ),
    ]
