# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Avocat', '0001_initial'),
        ('Client', '0001_initial'),
        ('Dossier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('statut_rdv', models.CharField(choices=[('prevu', 'Prévu'), ('reporte', 'Reporté'), ('réalise', 'Réalisé')], max_length=20)),
                ('avocat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Avocat.avocat')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.client')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier')),
            ],
        ),
    ]
