# Generated by Django 5.2.4 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseCreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100)),
                ('numeroRCCM', models.CharField(max_length=50)),
                ('numeroNIF', models.CharField(max_length=50)),
                ('siege', models.CharField(max_length=255)),
                ('nomGerant', models.CharField(max_length=100)),
                ('adresseGerant', models.CharField(max_length=255)),
                ('emailGerant', models.EmailField(max_length=254)),
                ('telephoneGerant', models.CharField(max_length=20)),
                ('date_creation', models.DateField()),
                ('documentation', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Entreprise Créée',
                'verbose_name_plural': 'Entreprises Créées',
                'ordering': ['-date_creation'],
                'unique_together': {('denomination', 'numeroRCCM')},
            },
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('commanditaire', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Etude',
                'verbose_name_plural': 'Etudes',
                'ordering': ['-date_debut'],
                'unique_together': {('intitule', 'date_debut')},
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certifiante', 'Certifiante'), ('atelier', 'Atelier'), ('seminaire', 'Séminaire')], default='certifiante', max_length=20)),
                ('theme', models.CharField(max_length=100)),
                ('nombre_participants', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
                'unique_together': {('theme', 'date_debut')},
            },
        ),
    ]
