# Generated by Django 5.2.4 on 2025-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, choices=[('penal', 'Droit pénal'), ('civil', 'Droit civil'), ('affaires', 'Droit des affaires'), ('travail', 'Droit du travail'), ('familial', 'Droit de la famille'), ('fiscal', 'Droit fiscal'), ('international', 'Droit international'), ('autre', 'Autre')], default='civil', max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avocat_photos/')),
                ('numero_barreau', models.CharField(blank=True, max_length=50, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
