# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriqueStatut', '0001_initial'),
        ('StatutDossier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestatut',
            name='modifié_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatutDossier.statutdossier'),
        ),
    ]
