# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Dossier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('moyen_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('url_facture', models.URLField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.client')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier')),
            ],
        ),
    ]
