# Generated by Django 5.2.4 on 2025-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('avocat', 'Avocat'), ('client', 'Client'), ('autre', 'Autre'), ('expert_metier', 'Expert Metier'), ('personnel_administratif', 'Personnel Administratif')], default='autre', max_length=50),
        ),
    ]
