# Generated by Django 5.2.4 on 2025-07-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dossier', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_evenement', models.DateTimeField()),
                ('type_evenement', models.CharField(choices=[('audience', 'Audience'), ('convocation', 'Convocation'), ('réunion', 'Réunion'), ('autre', 'Autre')], max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier')),
            ],
        ),
    ]
